data = [
    {"System": "Cardiovascular", "ICD-11": "11", "OSIICS": "", "Notes": "MC"},
    {"System": "Dermatological", "ICD-11": "14", "OSIICS": "", "Notes": "MD"},
    {"System": "Dental", "ICD-11": "(13)", "OSIICS": "", "Notes": "MT"},
    {"System": "Endocrinological", "ICD-11": "5", "OSIICS": "", "Notes": "MY"},
    {"System": "Gastrointestinal", "ICD-11": "(13)", "OSIICS": "", "Notes": "MG"},
    {
        "System": "Genitourinary",
        "ICD-11": "16",
        "OSIICS": "",
        "Notes": "Includes renal, obstetrical, gynecological",
    },
    {"System": "Hematologic", "ICD-11": "3", "OSIICS": "", "Notes": "MH"},
    {
        "System": "Musculoskeletal",
        "ICD-11": "15",
        "OSIICS": "",
        "Notes": "Includes rheumatological conditions",
    },
    {"System": "Neurological", "ICD-11": "8", "OSIICS": "", "Notes": "MN"},
    {"System": "Opthalmological", "ICD-11": "9", "OSIICS": "", "Notes": "MO"},
    {"System": "Otological", "ICD-11": "10", "OSIICS": "", "Notes": "Ear only"},
    {"System": "Psychiatric/psychological", "ICD-11": "6", "OSIICS": "", "Notes": "MS"},
    {
        "System": "Respiratory",
        "ICD-11": "12",
        "OSIICS": "",
        "Notes": "Includes nose and throat",
    },
    {"System": "Thermoregulatory", "ICD-11": "(22)", "OSIICS": "", "Notes": "MA"},
    {"System": "Multiple systems", "ICD-11": "", "OSIICS": "", "Notes": "MX"},
    {"System": "Unknown or not specified", "ICD-11": "", "OSIICS": "", "Notes": "MZ"},
]
