DELETE FROM "osiics.v14.ioc.categories";
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Head and neck','Head','H','Includes facial, brain (concussion), eyes, ears, teeth');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Head and neck','Neck','N','Cervical spine, throat');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Upper limb','Shoulder','S','Includes clavicle, scapula, rotator cuff, biceps tendon origin');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Upper limb','Upper Arm','U','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Upper limb','Elbow','E','Ligaments, insertional biceps and triceps tendon');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Upper limb','Forearm','R','Includes non-articular radius & ulna injuries');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Upper limb','Wrist','W','Carpus');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Upper limb','Hand','P','Includes finger, thumb');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Trunk','Chest','C','Sternum, ribs, chest organs');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Trunk','Thoracic spine','D','Thoracic spine, costovertebral joints');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Trunk','Lumbosacral','L','Includes lumbar spine, sacroiliac joints, sacrum, coccyx, buttock');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Trunk','Abdomen','O','Below diaphragm and above inguinal canal, includes abdominal organs');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Lower limb','Hip/Groin','G','Hip and anterior musculoskeletal structures (e.g. pubic symphysis, proximal adductors, iliopsoas)27 ');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Lower limb','Thigh','T','Includes femur, hamstrings (including ischial tuberosity), quadriceps, mid-distal adductors ');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Lower limb','Knee','K','Includes patella, patellar tendon, pes anserinus');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Lower limb','Leg','Q','Includes non-articular tibia & fibular injuries, calf and Achilles tendon');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Lower limb','Ankle','A','Includes syndesmosis, talocrural and subtalar joints');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Lower limb','Foot','F','Includes toes, calcaneus, plantar fascia');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Unspecified','Unspecified','Z','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Body_Area','Multiple regions','Single injury crossing two or more regions','X','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Muscle/tendon','Muscle injury','M','Includes strain, tear, rupture, intramuscular tendon');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Muscle contusion','H','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Muscle compartment syndrome','Y','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Tendinopathy','T','Includes paratenon, related bursa, fasciopathy, partial tear, tendon subluxation (all non-rupture), enthesopathy ');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Tendon rupture','R','Complete/full thickness injury; Partial tendon injuries considered to be tendinopathy');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Nervous','Brain & spinal cord injury','N','Includes concussion and all forms of brain injury, and spinal cord');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Peripheral nerve Injury','N','Includes neuroma');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Bone','Fracture','F','Traumatic, includes avulsion fracture, teeth');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Bone stress injury','S','Includes bone marrow edema, stress fracture, periostitis');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Bone contusion ','J','Acute bony traumatic injury without fracture. Osteochondral injuries are considered ‘Joint cartilage’');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Avascular necrosis','E','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Physis injury','G','Includes apophysis');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Cartilage/synovium/bursa','Cartilage','C','Includes meniscal, labral injuries and articular cartilage, osteochondral injuries');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Arthritis','A','Post traumatic osteoarthritis');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Synovitis / capsulitis','Q','Includes joint impingement');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Bursitis','B','Includes calcific bursitis, traumatic bursitis');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Ligament/joint capsule','Joint sprain (ligament tear or acute instability episode)','L or D','Includes partial and complete tears plus injuries to non-specific ligaments and joint capsule; includes joint dislocations / subluxations');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Chronic instability','U','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Superficial tissues/skin','Contusion (superficial)','V','Contusion, bruise, vascular damage');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Laceration','K','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','','Abrasion','I','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Vessels','Vascular trauma','V','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Stump','Stump injury','W','In amputees');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Internal organs','Organ trauma','O','Includes trauma to any organ (excluding concussion), drowning, relevant for all specialized organs not mentioned elsewhere (lungs, abdominal and pelvic organs, thyroid, breast)');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Tissue_Pathology','Non-specific','Injury without tissue type specified','P or Z','No specific tissue pathology diagnosed');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Cardiovascular','','MC','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Dermatological','','MD','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Dental','','MT','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Endocrinological','','MY','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Gastrointestinal','','MG','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Genitourinary','','MU','Includes renal, obstetrical, gynecological');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Hematologic','','MH','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Musculoskeletal','','MR','Includes rheumatological conditions');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Neurological','','MN','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Opthalmological','','MO','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Otological','','ME','Ear only');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Psychiatric/psychological','','MS','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Respiratory','','MP','Includes nose and throat');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Thermoregulatory','','MA','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Multiple systems','','MX','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Organ_System','Unknown or not specified','','MZ','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Allergic','','MxA','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Environmental–exercise-related','','MxE','Heat illness, hypothermia, hyponatraemia, dehydration ');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Environmental – non-exercise','','MxS','Includes sleep/wake, sunburn');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Immunological/inflammatory','','MxY','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Infection','','MxI','Viral, bacterial, parasitic');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Neoplasm','','MxB','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Metabolic/nutritional','','MxN','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Thrombotic/haemorrhagic','','MxV','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Degenerative or chronic condition','','MxC','Chronic acquired conditions');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Developmental anomaly','','MxJ','Includes congenital conditions');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Drug-related/poisoning','','MxD','Includes pharma, illicit');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Multiple','','MxX','');
INSERT OR REPLACE INTO "osiics.v14.ioc.categories" VALUES ('Etiology_Illness','Unknown, or not specified','','MxZ','');